### PR TITLE
Add smaug support and run in 2.17

### PR DESCRIPTION
**Pull request by Eric-Guo**

### CODE REVIEW

**Comment by Rabios** [comment]
OK, Done and thanks for your support! ❤️

**Comment by Eric-Guo** [comment]
I'm still learning, but I found using https://smaug.dev for dragon ruby is much more comfortable way to try things, `smaug run` is able to running any folder, not must inside the dragonruby folder before.

**Comment by Rabios** [comment]
It works well, Right?
(I mean about the package, It's fine as will fix things if not along with releasing drtouch soon)

**Comment by Eric-Guo** [comment]
I not yet start writing package, but Smaug works well for using package projects, like [flappy-coin-collector](https://github.com/ereborstudios/flappy-coin-collector)

**Pull request merged**
